/*
 * GOOFR Store
 * API documentation for GOOFR Store, a digital game store.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help.goofrportugal@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ClientAccessSchema model module.
 * @module model/ClientAccessSchema
 * @version 1.0.0
 */
export class ClientAccessSchema {
  /**
   * Constructs a new <code>ClientAccessSchema</code>.
   * @alias module:model/ClientAccessSchema
   * @class
   * @param oauth {Boolean} 
   * @param email {String} 
   */
  constructor(oauth, email) {
    this.oauth = oauth;
    this.email = email;
  }

  /**
   * Constructs a <code>ClientAccessSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClientAccessSchema} obj Optional instance to populate.
   * @return {module:model/ClientAccessSchema} The populated <code>ClientAccessSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClientAccessSchema();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('id_client'))
        obj.idClient = ApiClient.convertToType(data['id_client'], 'String');
      if (data.hasOwnProperty('oauth'))
        obj.oauth = ApiClient.convertToType(data['oauth'], 'Boolean');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
ClientAccessSchema.prototype.id = undefined;

/**
 * @member {String} idClient
 */
ClientAccessSchema.prototype.idClient = undefined;

/**
 * @member {Boolean} oauth
 */
ClientAccessSchema.prototype.oauth = undefined;

/**
 * @member {String} email
 */
ClientAccessSchema.prototype.email = undefined;

/**
 * @member {String} password
 */
ClientAccessSchema.prototype.password = undefined;

