/*
 * GOOFR Store
 * API documentation for GOOFR Store, a digital game store.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help.goofrportugal@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ClientAddressSchema model module.
 * @module model/ClientAddressSchema
 * @version 1.0.0
 */
export class ClientAddressSchema {
  /**
   * Constructs a new <code>ClientAddressSchema</code>.
   * @alias module:model/ClientAddressSchema
   * @class
   * @param street {String} 
   * @param zipCode {String} 
   * @param city {String} 
   * @param country {String} 
   */
  constructor(street, zipCode, city, country) {
    this.street = street;
    this.zipCode = zipCode;
    this.city = city;
    this.country = country;
  }

  /**
   * Constructs a <code>ClientAddressSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClientAddressSchema} obj Optional instance to populate.
   * @return {module:model/ClientAddressSchema} The populated <code>ClientAddressSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClientAddressSchema();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('id_client'))
        obj.idClient = ApiClient.convertToType(data['id_client'], 'String');
      if (data.hasOwnProperty('street'))
        obj.street = ApiClient.convertToType(data['street'], 'String');
      if (data.hasOwnProperty('door_number'))
        obj.doorNumber = ApiClient.convertToType(data['door_number'], 'String');
      if (data.hasOwnProperty('zip_code'))
        obj.zipCode = ApiClient.convertToType(data['zip_code'], 'String');
      if (data.hasOwnProperty('city'))
        obj.city = ApiClient.convertToType(data['city'], 'String');
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
ClientAddressSchema.prototype.id = undefined;

/**
 * @member {String} idClient
 */
ClientAddressSchema.prototype.idClient = undefined;

/**
 * @member {String} street
 */
ClientAddressSchema.prototype.street = undefined;

/**
 * @member {String} doorNumber
 */
ClientAddressSchema.prototype.doorNumber = undefined;

/**
 * @member {String} zipCode
 */
ClientAddressSchema.prototype.zipCode = undefined;

/**
 * @member {String} city
 */
ClientAddressSchema.prototype.city = undefined;

/**
 * @member {String} country
 */
ClientAddressSchema.prototype.country = undefined;

