/*
 * GOOFR Store
 * API documentation for GOOFR Store, a digital game store.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help.goofrportugal@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GameImageSchema model module.
 * @module model/GameImageSchema
 * @version 1.0.0
 */
export class GameImageSchema {
  /**
   * Constructs a new <code>GameImageSchema</code>.
   * @alias module:model/GameImageSchema
   * @class
   * @param id {String} 
   * @param idGame {String} 
   * @param image {String} 
   */
  constructor(id, idGame, image) {
    this.id = id;
    this.idGame = idGame;
    this.image = image;
  }

  /**
   * Constructs a <code>GameImageSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GameImageSchema} obj Optional instance to populate.
   * @return {module:model/GameImageSchema} The populated <code>GameImageSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GameImageSchema();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('id_game'))
        obj.idGame = ApiClient.convertToType(data['id_game'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GameImageSchema.prototype.id = undefined;

/**
 * @member {String} idGame
 */
GameImageSchema.prototype.idGame = undefined;

/**
 * @member {String} image
 */
GameImageSchema.prototype.image = undefined;

