/*
 * GOOFR Store
 * API documentation for GOOFR Store, a digital game store.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help.goofrportugal@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InvoiceGameSchema model module.
 * @module model/InvoiceGameSchema
 * @version 1.0.0
 */
export class InvoiceGameSchema {
  /**
   * Constructs a new <code>InvoiceGameSchema</code>.
   * @alias module:model/InvoiceGameSchema
   * @class
   * @param idGame {String} 
   * @param price {Number} 
   * @param discount {Number} 
   */
  constructor(idGame, price, discount) {
    this.idGame = idGame;
    this.price = price;
    this.discount = discount;
  }

  /**
   * Constructs a <code>InvoiceGameSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InvoiceGameSchema} obj Optional instance to populate.
   * @return {module:model/InvoiceGameSchema} The populated <code>InvoiceGameSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InvoiceGameSchema();
      if (data.hasOwnProperty('id_game'))
        obj.idGame = ApiClient.convertToType(data['id_game'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
      if (data.hasOwnProperty('discount'))
        obj.discount = ApiClient.convertToType(data['discount'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} idGame
 */
InvoiceGameSchema.prototype.idGame = undefined;

/**
 * @member {Number} price
 */
InvoiceGameSchema.prototype.price = undefined;

/**
 * @member {Number} discount
 */
InvoiceGameSchema.prototype.discount = undefined;

