/*
 * GOOFR Store
 * API documentation for GOOFR Store, a digital game store.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help.goofrportugal@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GameSchema} from './GameSchema';

/**
 * The NewsletterBodySchema model module.
 * @module model/NewsletterBodySchema
 * @version 1.0.0
 */
export class NewsletterBodySchema {
  /**
   * Constructs a new <code>NewsletterBodySchema</code>.
   * @alias module:model/NewsletterBodySchema
   * @class
   * @param title {String} 
   * @param games {Array.<module:model/GameSchema>} 
   */
  constructor(title, games) {
    this.title = title;
    this.games = games;
  }

  /**
   * Constructs a <code>NewsletterBodySchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NewsletterBodySchema} obj Optional instance to populate.
   * @return {module:model/NewsletterBodySchema} The populated <code>NewsletterBodySchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NewsletterBodySchema();
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('games'))
        obj.games = ApiClient.convertToType(data['games'], [GameSchema]);
    }
    return obj;
  }
}

/**
 * @member {String} title
 */
NewsletterBodySchema.prototype.title = undefined;

/**
 * @member {Array.<module:model/GameSchema>} games
 */
NewsletterBodySchema.prototype.games = undefined;

