/*
 * GOOFR Store
 * API documentation for GOOFR Store, a digital game store.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help.goofrportugal@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GameSchema} from './GameSchema';

/**
 * The NoteworthyStoreSchema model module.
 * @module model/NoteworthyStoreSchema
 * @version 1.0.0
 */
export class NoteworthyStoreSchema {
  /**
   * Constructs a new <code>NoteworthyStoreSchema</code>.
   * @alias module:model/NoteworthyStoreSchema
   * @class
   * @param featured {Array.<module:model/GameSchema>} 
   * @param noteworthy {Array.<module:model/GameSchema>} 
   */
  constructor(featured, noteworthy) {
    this.featured = featured;
    this.noteworthy = noteworthy;
  }

  /**
   * Constructs a <code>NoteworthyStoreSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NoteworthyStoreSchema} obj Optional instance to populate.
   * @return {module:model/NoteworthyStoreSchema} The populated <code>NoteworthyStoreSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NoteworthyStoreSchema();
      if (data.hasOwnProperty('featured'))
        obj.featured = ApiClient.convertToType(data['featured'], [GameSchema]);
      if (data.hasOwnProperty('noteworthy'))
        obj.noteworthy = ApiClient.convertToType(data['noteworthy'], [GameSchema]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/GameSchema>} featured
 */
NoteworthyStoreSchema.prototype.featured = undefined;

/**
 * @member {Array.<module:model/GameSchema>} noteworthy
 */
NoteworthyStoreSchema.prototype.noteworthy = undefined;

