/*
 * GOOFR Store
 * API documentation for GOOFR Store, a digital game store.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help.goofrportugal@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PublisherSchema model module.
 * @module model/PublisherSchema
 * @version 1.0.0
 */
export class PublisherSchema {
  /**
   * Constructs a new <code>PublisherSchema</code>.
   * @alias module:model/PublisherSchema
   * @class
   * @param name {String} 
   * @param coverImage {String} 
   * @param phoneNumber {String} 
   * @param email {String} 
   */
  constructor(name, coverImage, phoneNumber, email) {
    this.name = name;
    this.coverImage = coverImage;
    this.phoneNumber = phoneNumber;
    this.email = email;
  }

  /**
   * Constructs a <code>PublisherSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PublisherSchema} obj Optional instance to populate.
   * @return {module:model/PublisherSchema} The populated <code>PublisherSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PublisherSchema();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('cover_image'))
        obj.coverImage = ApiClient.convertToType(data['cover_image'], 'String');
      if (data.hasOwnProperty('phone_number'))
        obj.phoneNumber = ApiClient.convertToType(data['phone_number'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
PublisherSchema.prototype.id = undefined;

/**
 * @member {String} name
 */
PublisherSchema.prototype.name = undefined;

/**
 * @member {String} coverImage
 */
PublisherSchema.prototype.coverImage = undefined;

/**
 * @member {String} phoneNumber
 */
PublisherSchema.prototype.phoneNumber = undefined;

/**
 * @member {String} email
 */
PublisherSchema.prototype.email = undefined;

