/*
 * GOOFR Store
 * API documentation for GOOFR Store, a digital game store.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help.goofrportugal@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ClientAccessSchema} from './ClientAccessSchema';
import {ClientAddressSchema} from './ClientAddressSchema';
import {ClientSchema} from './ClientSchema';
import {ClientWalletSchema} from './ClientWalletSchema';

/**
 * The RegisterClientSchema model module.
 * @module model/RegisterClientSchema
 * @version 1.0.0
 */
export class RegisterClientSchema {
  /**
   * Constructs a new <code>RegisterClientSchema</code>.
   * @alias module:model/RegisterClientSchema
   * @class
   * @param client {module:model/ClientSchema} 
   * @param access {module:model/ClientAccessSchema} 
   * @param address {module:model/ClientAddressSchema} 
   * @param wallet {module:model/ClientWalletSchema} 
   */
  constructor(client, access, address, wallet) {
    this.client = client;
    this.access = access;
    this.address = address;
    this.wallet = wallet;
  }

  /**
   * Constructs a <code>RegisterClientSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RegisterClientSchema} obj Optional instance to populate.
   * @return {module:model/RegisterClientSchema} The populated <code>RegisterClientSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RegisterClientSchema();
      if (data.hasOwnProperty('client'))
        obj.client = ClientSchema.constructFromObject(data['client']);
      if (data.hasOwnProperty('access'))
        obj.access = ClientAccessSchema.constructFromObject(data['access']);
      if (data.hasOwnProperty('address'))
        obj.address = ClientAddressSchema.constructFromObject(data['address']);
      if (data.hasOwnProperty('wallet'))
        obj.wallet = ClientWalletSchema.constructFromObject(data['wallet']);
    }
    return obj;
  }
}

/**
 * @member {module:model/ClientSchema} client
 */
RegisterClientSchema.prototype.client = undefined;

/**
 * @member {module:model/ClientAccessSchema} access
 */
RegisterClientSchema.prototype.access = undefined;

/**
 * @member {module:model/ClientAddressSchema} address
 */
RegisterClientSchema.prototype.address = undefined;

/**
 * @member {module:model/ClientWalletSchema} wallet
 */
RegisterClientSchema.prototype.wallet = undefined;

