/*
 * GOOFR Store
 * API documentation for GOOFR Store, a digital game store.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help.goofrportugal@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ReviewSchema model module.
 * @module model/ReviewSchema
 * @version 1.0.0
 */
export class ReviewSchema {
  /**
   * Constructs a new <code>ReviewSchema</code>.
   * @alias module:model/ReviewSchema
   * @class
   * @param idGame {String} 
   * @param idClient {String} 
   */
  constructor(idGame, idClient) {
    this.idGame = idGame;
    this.idClient = idClient;
  }

  /**
   * Constructs a <code>ReviewSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReviewSchema} obj Optional instance to populate.
   * @return {module:model/ReviewSchema} The populated <code>ReviewSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReviewSchema();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('id_game'))
        obj.idGame = ApiClient.convertToType(data['id_game'], 'String');
      if (data.hasOwnProperty('id_client'))
        obj.idClient = ApiClient.convertToType(data['id_client'], 'String');
      if (data.hasOwnProperty('stars'))
        obj.stars = ApiClient.convertToType(data['stars'], 'Number');
      if (data.hasOwnProperty('review'))
        obj.review = ApiClient.convertToType(data['review'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
ReviewSchema.prototype.id = undefined;

/**
 * @member {String} idGame
 */
ReviewSchema.prototype.idGame = undefined;

/**
 * @member {String} idClient
 */
ReviewSchema.prototype.idClient = undefined;

/**
 * @member {Number} stars
 */
ReviewSchema.prototype.stars = undefined;

/**
 * @member {String} review
 */
ReviewSchema.prototype.review = undefined;

