/*
 * GOOFR Store
 * API documentation for GOOFR Store, a digital game store.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help.goofrportugal@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GameSchema} from './GameSchema';

/**
 * The TopReviewsSchema model module.
 * @module model/TopReviewsSchema
 * @version 1.0.0
 */
export class TopReviewsSchema {
  /**
   * Constructs a new <code>TopReviewsSchema</code>.
   * @alias module:model/TopReviewsSchema
   * @class
   * @param game {module:model/GameSchema} 
   * @param average {Number} 
   */
  constructor(game, average) {
    this.game = game;
    this.average = average;
  }

  /**
   * Constructs a <code>TopReviewsSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TopReviewsSchema} obj Optional instance to populate.
   * @return {module:model/TopReviewsSchema} The populated <code>TopReviewsSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TopReviewsSchema();
      if (data.hasOwnProperty('game'))
        obj.game = GameSchema.constructFromObject(data['game']);
      if (data.hasOwnProperty('average'))
        obj.average = ApiClient.convertToType(data['average'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {module:model/GameSchema} game
 */
TopReviewsSchema.prototype.game = undefined;

/**
 * @member {Number} average
 */
TopReviewsSchema.prototype.average = undefined;

