/*
 * GOOFR Store
 * API documentation for GOOFR Store, a digital game store.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help.goofrportugal@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The VersionSchema model module.
 * @module model/VersionSchema
 * @version 1.0.0
 */
export class VersionSchema {
  /**
   * Constructs a new <code>VersionSchema</code>.
   * @alias module:model/VersionSchema
   * @class
   * @param version {String} 
   * @param notes {String} 
   */
  constructor(version, notes) {
    this.version = version;
    this.notes = notes;
  }

  /**
   * Constructs a <code>VersionSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VersionSchema} obj Optional instance to populate.
   * @return {module:model/VersionSchema} The populated <code>VersionSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VersionSchema();
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
      if (data.hasOwnProperty('notes'))
        obj.notes = ApiClient.convertToType(data['notes'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} version
 */
VersionSchema.prototype.version = undefined;

/**
 * @member {String} notes
 */
VersionSchema.prototype.notes = undefined;

