/*
 * GOOFR Store
 * API documentation for GOOFR Store, a digital game store.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: help.goofrportugal@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {BestSellersSchema} from './model/BestSellersSchema';
import {ClientAccessSchema} from './model/ClientAccessSchema';
import {ClientAddressSchema} from './model/ClientAddressSchema';
import {ClientSchema} from './model/ClientSchema';
import {ClientWalletSchema} from './model/ClientWalletSchema';
import {ErrorSchema} from './model/ErrorSchema';
import {GameImageSchema} from './model/GameImageSchema';
import {GameSchema} from './model/GameSchema';
import {InvoiceGameSchema} from './model/InvoiceGameSchema';
import {InvoiceSchema} from './model/InvoiceSchema';
import {NewStoreSchema} from './model/NewStoreSchema';
import {NewsletterBodySchema} from './model/NewsletterBodySchema';
import {NewsletterSchema} from './model/NewsletterSchema';
import {NoteworthyStoreSchema} from './model/NoteworthyStoreSchema';
import {PublisherSchema} from './model/PublisherSchema';
import {RegisterClientSchema} from './model/RegisterClientSchema';
import {ReviewSchema} from './model/ReviewSchema';
import {SearchSchema} from './model/SearchSchema';
import {TagSchema} from './model/TagSchema';
import {TopReviewsSchema} from './model/TopReviewsSchema';
import {VersionSchema} from './model/VersionSchema';
import {YourStoreSchema} from './model/YourStoreSchema';
import {AccessApi} from './api/AccessApi';
import {AddressApi} from './api/AddressApi';
import {CartApi} from './api/CartApi';
import {ClientApi} from './api/ClientApi';
import {GameApi} from './api/GameApi';
import {InvoiceApi} from './api/InvoiceApi';
import {LibraryApi} from './api/LibraryApi';
import {NewsletterApi} from './api/NewsletterApi';
import {PublisherApi} from './api/PublisherApi';
import {ReviewApi} from './api/ReviewApi';
import {SearchApi} from './api/SearchApi';
import {ServerApi} from './api/ServerApi';
import {StatisticsApi} from './api/StatisticsApi';
import {StoreApi} from './api/StoreApi';
import {TagApi} from './api/TagApi';
import {WalletApi} from './api/WalletApi';
import {WishlistApi} from './api/WishlistApi';

/**
* API_documentation_for_GOOFR_Store_a_digital_game_store_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var GoofrStore = require('index'); // See note below*.
* var xxxSvc = new GoofrStore.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new GoofrStore.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new GoofrStore.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new GoofrStore.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BestSellersSchema model constructor.
     * @property {module:model/BestSellersSchema}
     */
    BestSellersSchema,

    /**
     * The ClientAccessSchema model constructor.
     * @property {module:model/ClientAccessSchema}
     */
    ClientAccessSchema,

    /**
     * The ClientAddressSchema model constructor.
     * @property {module:model/ClientAddressSchema}
     */
    ClientAddressSchema,

    /**
     * The ClientSchema model constructor.
     * @property {module:model/ClientSchema}
     */
    ClientSchema,

    /**
     * The ClientWalletSchema model constructor.
     * @property {module:model/ClientWalletSchema}
     */
    ClientWalletSchema,

    /**
     * The ErrorSchema model constructor.
     * @property {module:model/ErrorSchema}
     */
    ErrorSchema,

    /**
     * The GameImageSchema model constructor.
     * @property {module:model/GameImageSchema}
     */
    GameImageSchema,

    /**
     * The GameSchema model constructor.
     * @property {module:model/GameSchema}
     */
    GameSchema,

    /**
     * The InvoiceGameSchema model constructor.
     * @property {module:model/InvoiceGameSchema}
     */
    InvoiceGameSchema,

    /**
     * The InvoiceSchema model constructor.
     * @property {module:model/InvoiceSchema}
     */
    InvoiceSchema,

    /**
     * The NewStoreSchema model constructor.
     * @property {module:model/NewStoreSchema}
     */
    NewStoreSchema,

    /**
     * The NewsletterBodySchema model constructor.
     * @property {module:model/NewsletterBodySchema}
     */
    NewsletterBodySchema,

    /**
     * The NewsletterSchema model constructor.
     * @property {module:model/NewsletterSchema}
     */
    NewsletterSchema,

    /**
     * The NoteworthyStoreSchema model constructor.
     * @property {module:model/NoteworthyStoreSchema}
     */
    NoteworthyStoreSchema,

    /**
     * The PublisherSchema model constructor.
     * @property {module:model/PublisherSchema}
     */
    PublisherSchema,

    /**
     * The RegisterClientSchema model constructor.
     * @property {module:model/RegisterClientSchema}
     */
    RegisterClientSchema,

    /**
     * The ReviewSchema model constructor.
     * @property {module:model/ReviewSchema}
     */
    ReviewSchema,

    /**
     * The SearchSchema model constructor.
     * @property {module:model/SearchSchema}
     */
    SearchSchema,

    /**
     * The TagSchema model constructor.
     * @property {module:model/TagSchema}
     */
    TagSchema,

    /**
     * The TopReviewsSchema model constructor.
     * @property {module:model/TopReviewsSchema}
     */
    TopReviewsSchema,

    /**
     * The VersionSchema model constructor.
     * @property {module:model/VersionSchema}
     */
    VersionSchema,

    /**
     * The YourStoreSchema model constructor.
     * @property {module:model/YourStoreSchema}
     */
    YourStoreSchema,

    /**
    * The AccessApi service constructor.
    * @property {module:api/AccessApi}
    */
    AccessApi,

    /**
    * The AddressApi service constructor.
    * @property {module:api/AddressApi}
    */
    AddressApi,

    /**
    * The CartApi service constructor.
    * @property {module:api/CartApi}
    */
    CartApi,

    /**
    * The ClientApi service constructor.
    * @property {module:api/ClientApi}
    */
    ClientApi,

    /**
    * The GameApi service constructor.
    * @property {module:api/GameApi}
    */
    GameApi,

    /**
    * The InvoiceApi service constructor.
    * @property {module:api/InvoiceApi}
    */
    InvoiceApi,

    /**
    * The LibraryApi service constructor.
    * @property {module:api/LibraryApi}
    */
    LibraryApi,

    /**
    * The NewsletterApi service constructor.
    * @property {module:api/NewsletterApi}
    */
    NewsletterApi,

    /**
    * The PublisherApi service constructor.
    * @property {module:api/PublisherApi}
    */
    PublisherApi,

    /**
    * The ReviewApi service constructor.
    * @property {module:api/ReviewApi}
    */
    ReviewApi,

    /**
    * The SearchApi service constructor.
    * @property {module:api/SearchApi}
    */
    SearchApi,

    /**
    * The ServerApi service constructor.
    * @property {module:api/ServerApi}
    */
    ServerApi,

    /**
    * The StatisticsApi service constructor.
    * @property {module:api/StatisticsApi}
    */
    StatisticsApi,

    /**
    * The StoreApi service constructor.
    * @property {module:api/StoreApi}
    */
    StoreApi,

    /**
    * The TagApi service constructor.
    * @property {module:api/TagApi}
    */
    TagApi,

    /**
    * The WalletApi service constructor.
    * @property {module:api/WalletApi}
    */
    WalletApi,

    /**
    * The WishlistApi service constructor.
    * @property {module:api/WishlistApi}
    */
    WishlistApi
};
